# Generated by Django 4.1.6 on 2023-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tasks', models.TextField()),
                ('Status', models.TextField(choices=[('Done', 'Done'), ('Active', 'Active'), ('Deleted', 'Deleted')])),
            ],
        ),
    ]
